//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPrimeraAplicacionWebConEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVC_Cliente
    {
        public int IdCliente { get; set; }
        public string Nombre { get; set; }
        public int IdSexo { get; set; }
        public Nullable<int> BHabilitado { get; set; }
        public string Telefono { get; set; }
    
        public virtual MVC_Sexo MVC_Sexo { get; set; }
    }
}
