//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiPrimeraAplicacionWebConEntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVC_Sexo
    {
        public MVC_Sexo()
        {
            this.MVC_Cliente = new HashSet<MVC_Cliente>();
        }
    
        public int IdSexo { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> BHabilitado { get; set; }
    
        public virtual ICollection<MVC_Cliente> MVC_Cliente { get; set; }
    }
}
